import { albertSans, barlow } from "@/assets/fonts/Fonts";
import "./globals.css";
import { Metadata } from "next";
import AuthProvider from "@/components/authProvider/AuthProvider";

export const metadata: Metadata = {
  title: "Client Relationship Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${albertSans.variable} ${barlow.variable}`}>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
